<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-PH7A2OE" failures="1" tests="4" name="Adding customer " time="17.626" errors="0" timestamp="2020-04-17T12:08:25 IST">
  <testcase classname="com.w2a.testcases.AddCust" name="add" time="5.682"/>
  <testcase classname="com.w2a.testcases.AddCust" name="add" time="5.339"/>
  <testcase classname="com.w2a.testcases.AddCust" name="add" time="5.286"/>
  <testcase classname="com.w2a.testcases.AddCust" name="check" time="0.003">
    <failure type="java.lang.AssertionError" message="we make this test to faile">
      <![CDATA[java.lang.AssertionError: we make this test to faile
at com.w2a.testcases.AddCust.check(AddCust.java:43)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- check -->
</testsuite> <!-- Adding customer  -->
